language: node_js
sudo: false
node_js:
  - '10.15.2'
cache:
  directories:
    - node_modules
jobs:
  include:
    - stage: lint
      script: npm run lint

    - stage: unit-test
      script: npm run test
